services:
  app:
    image: ghcr.io/alexpovel/aicalamba:main
    platform: linux/amd64 # if on Apple Silicon
    depends_on:
      - chromedriver
    ports:
      - "3000:3000"
    environment:
      CHROME_DRIVER_URL: http://chromedriver:4444
      OPENAI_KEY: "${OPENAI_KEY:-}"

  chromedriver:
    image: selenium/standalone-chrome
    shm_size: '2gb'
    platform: linux/amd64 # if on Apple Silicon
    environment:
      SE_ENABLE_TRACING: "false" # https://github.com/SeleniumHQ/docker-selenium/issues/2355
    ports:
      - "4444:4444"
